name: Merge

on:
  push:
    branches:
      - main

jobs:
  gettext:
    name: Gettext
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Gettext
        uses: elementary/actions/gettext-template@horus
        env:
          GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
          GIT_USER_NAME: "elementaryBot"
          GIT_USER_EMAIL: "builds@elementary.io"
